### ISSUE TITLE
Help - Bunny Hop

### ISSUE THREAD

**Issue by ItsukaHiro** [Emonadeo/AutoRun#13]
Though there is an option to called "Auto - Jump", I still dont know how to perform Bunny Hop (Continuous jump while sprinting - sorry for my english).
If the mod hasn't this function yet, I hope - there is a update, asap °-°

**Comment by emonadeo** [comment]
Auto-Jump refers to the Auto-Jump the vanilla game already has implemented. That is automatically jumping when encountering an 1-block tall obstacle.

I don't have plans to add B-Hopping to this mod, but I am not fully against it either.

* it adds complexity which goes against this mod's philosophy of being a very bare and super-simple utility mod that adds and only adds "Press a key -> Auto-Run".
* it's not that much faster than sprinting
* it kills the hunger bar. Having to eat every minute seems counter intuitive unless I also add auto-eat to this mod.

I also feel like this is a niche request.
Closing for now. Might reopen if more people ask for this.
