### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Echo69420** [Emonadeo/AutoRun#18]
Simply not working 1.20.1. Do I need mod menu?

**Comment by emonadeo** [comment]
You don't need Mod Menu. Maybe you have other mods installed, which might conflict with this mod. Can you reply with the crash log?

I just tested AutoRun v0.5.0 in Minecraft 1.20.1 with Fabric Loader 0.15.1 and Fabric API 0.91.0 without any problems.

**Comment by Echo69420** [comment]
I’m always messing up with the opening of issues on GitHub lmao but yeah I’m sorry I shouldn’t even have came here first I’ll test without all my mods and figure out which one it is if that’s the problem
