### ISSUE TITLE
Suggestion: Notification on Auto-run toggle

### ISSUE THREAD

**Issue by Onewingseraphim** [Emonadeo/AutoRun#24]
Don't know if it's present in newer versions as I play on 1.19.2 but was wondering if you could add a simple Auto-Run ON/OFF text on the action bar so you know when it's enabled or even some sort of icon to show it's enabled :) this mod is the only automove mod I could find working for my version and it's been super nice especially on boats and other things etc. Would love to see config options and maybe other features.

**Comment by emonadeo** [comment]
Added in v1.0.0. Now shows a client-side text in chat. Might revisit this in the future and make it look a little nicer. Perhaps with a subtle icon on the hotbar or crosshair (similar to the attack recharge)
