### ISSUE TITLE
getting disconnected on entering any server

### ISSUE THREAD

**Issue by kimitaka9x** [Emonadeo/AutoRun#26]
Hi! After installing the mod, Minecraft starts, but doesn't let me enter any server. I tested it only with Fabric Api, Mod Menu and Autorun. I'm attaching the disconnect log. Thank you. I would really love to use your mod! 
[disconnect-2024-11-06_16.18.21-client.txt](https://github.com/user-attachments/files/17642665/disconnect-2024-11-06_16.18.21-client.txt)

**Comment by emonadeo** [comment]
This happens when running the mod in 1.21.2-pre or newer. Fixed in v1.0.0.
